import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../generated/prisma/client.js'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

const rules = [
  // ─── CRITICAL (weight: -25) ───────────────────────────────────────────
  {
    code: 'REG-002',
    domain: 'Registration',
    displayName: 'NDIS registration certificate uploaded and current',
    description: 'The provider must hold a current NDIS registration certificate and keep a copy accessible for audit. Lapsed registration means operating unlawfully.',
    officialRef: 'Provider Registration Rules 2018, Part 2',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'A valid, non-expired NDIS registration certificate PDF is stored in the evidence repository',
    evidenceRequired: 'Current registration certificate PDF',
    remediation: 'Upload current NDIS registration certificate. If expired, contact NDIS Commission immediately to renew.',
  },
  {
    code: 'REG-009',
    domain: 'Registration',
    displayName: 'Public liability and professional indemnity insurance current',
    description: 'Provider must maintain public liability and professional indemnity insurance with adequate coverage as a condition of registration.',
    officialRef: 'Provider Registration Rules 2018, Rule 11',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Both public liability and professional indemnity insurance certificates are on file and have expiry dates in the future',
    evidenceRequired: 'Current insurance certificates with sums insured',
    remediation: 'Upload current insurance certificates. Ensure policies show minimum required coverage and are not expired.',
  },
  {
    code: 'RR-003',
    domain: 'Rights & Responsibilities',
    displayName: 'Service agreement in place with each participant',
    description: 'Every participant must have a signed service agreement before services commence, covering scope, fees, cancellation, and complaints process.',
    officialRef: 'Practice Standards, Verification Module, Outcome 2.1',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 74',
    severity: 'CRITICAL',
    weight: -25,
    condition: 'All active participants have a signed service agreement on file with date prior to first service delivery',
    evidenceRequired: 'Signed service agreement or online acceptance with timestamp',
    remediation: 'Obtain signed service agreements for all participants missing them. Halt services for any participant without an agreement until one is executed.',
  },
  {
    code: 'RR-005',
    domain: 'Rights & Responsibilities',
    displayName: 'Privacy policy referencing Privacy Act 1988 and NDIS Act',
    description: 'A current privacy policy must be in place that references both the Privacy Act 1988 and NDIS Act, and is provided to participants.',
    officialRef: 'Practice Standards, Verification Module, Outcome 1.4',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Privacy policy document exists, references both Privacy Act 1988 and NDIS Act 2013, and has a current review date',
    evidenceRequired: 'Privacy policy document citing both Acts',
    remediation: 'Create or update privacy policy to explicitly reference Privacy Act 1988 (including APPs) and NDIS Act 2013. Ensure it is provided to all participants.',
  },
  {
    code: 'RR-006',
    domain: 'Rights & Responsibilities',
    displayName: 'Signed consent to collect/share per participant',
    description: 'Each participant must provide informed consent for the collection, use, and disclosure of their personal information.',
    officialRef: 'Practice Standards, Verification Module, Outcome 1.4',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Every active participant has a signed consent form or service agreement clause authorising data collection/sharing',
    evidenceRequired: 'Consent form or service agreement clause with participant sign-off',
    remediation: 'Obtain signed consent from all participants missing it. Include consent clause in service agreement template for new participants.',
  },
  {
    code: 'GOV-005',
    domain: 'Governance',
    displayName: 'Incident management system with required fields',
    description: 'An incident management system must capture all mandatory fields: date, participant, description, severity, actions taken, and closure status.',
    officialRef: 'Practice Standards, Verification Module, Outcome 1.6',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 73',
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Incident register exists with fields: date, participant, description, severity, actions taken, and closure status all populated',
    evidenceRequired: 'Incident register with date, participant, description, severity, actions, closure',
    remediation: 'Configure incident management system to require all mandatory fields. Backfill any existing records missing data.',
  },
  {
    code: 'GOV-006',
    domain: 'Governance',
    displayName: 'Reportable incident notified within 24 hours',
    description: 'Reportable incidents must be notified to the NDIS Commission within 24 hours of the provider becoming aware.',
    officialRef: 'NDIS (Incident Management) Rules 2018, Rule 11',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'All reportable incidents have a Commission notification timestamp within 24 hours of awareness date',
    evidenceRequired: 'Notification record with timestamp within 24hrs of awareness',
    remediation: 'Establish process for immediate identification and 24hr notification of reportable incidents. Document all notifications with timestamps.',
  },
  {
    code: 'GOV-010',
    domain: 'Governance',
    displayName: 'Complaints register — acknowledged, assessed, resolved',
    description: 'A complaints register must track the full lifecycle: receipt, acknowledgement, assessment, resolution, and outcome notification.',
    officialRef: 'Practice Standards, Verification Module, Outcome 1.5',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 75',
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Complaints register exists showing acknowledgement, assessment, and resolution stages for each complaint',
    evidenceRequired: 'Complaints register showing full lifecycle per complaint',
    remediation: 'Implement complaints register with mandatory lifecycle stages. Update any incomplete complaint records.',
  },
  {
    code: 'GOV-017',
    domain: 'Governance',
    displayName: 'Conflict of interest register maintained',
    description: 'A conflict of interest register must be maintained with declarations from all key personnel and workers in decision-making roles.',
    officialRef: 'Practice Standards, Verification Module, Outcome 1.1',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'COI register exists with current declarations from all key personnel',
    evidenceRequired: 'COI register with declarations',
    remediation: 'Create conflict of interest register. Obtain declarations from all key personnel and review annually.',
  },
  {
    code: 'WF-001',
    domain: 'Workforce',
    displayName: 'NDIS Worker Screening Check current for all workers',
    description: 'All workers engaged by the provider must hold a current NDIS Worker Screening Check clearance before commencing work with participants.',
    officialRef: 'Practice Standards (Worker Screening) Rules 2018',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 77',
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Every active worker has a valid NDIS Worker Screening Check with expiry date in the future',
    evidenceRequired: 'Valid screening certificates with expiry dates for all staff',
    remediation: 'Immediately stand down any worker without a current screening clearance. Lodge screening applications and do not assign participants until cleared.',
  },
  {
    code: 'WF-005',
    domain: 'Workforce',
    displayName: 'NDIS Code of Conduct signed by all workers and key personnel',
    description: 'All workers and key personnel must acknowledge the NDIS Code of Conduct in writing.',
    officialRef: 'NDIS Code of Conduct Rules 2018, Rule 3',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Signed Code of Conduct acknowledgement on file for every active worker and key personnel',
    evidenceRequired: 'Signed Code of Conduct acknowledgements per worker',
    remediation: 'Distribute NDIS Code of Conduct to all workers and key personnel. Collect signed acknowledgements and file them.',
  },
  {
    code: 'POS-004',
    domain: 'Provision of Supports',
    displayName: 'Claims match plan budget categories',
    description: 'All claims submitted to the NDIA must align with the support categories and line items in the participant\'s approved plan.',
    officialRef: 'NDIS Act 2013, Section 46',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Every claim submitted matches a valid support category in the participant\'s current NDIS plan',
    evidenceRequired: 'Evidence claims align with participant plan categories',
    remediation: 'Implement claim validation against plan categories before submission. Investigate and correct any miscategorised claims.',
  },
  {
    code: 'POS-006',
    domain: 'Provision of Supports',
    displayName: 'Every billable contact has timestamped note',
    description: 'Each billable service contact must have a corresponding timestamped service note documenting what was delivered.',
    officialRef: 'Practice Standards, Verification Module, Outcome 2.4',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'All billable contacts have a corresponding service note with date, time, and description',
    evidenceRequired: 'Service records with date, time, description per interaction',
    remediation: 'Require service notes for every billable interaction. Audit recent claims for missing notes and backfill documentation.',
  },
  {
    code: 'POS-009',
    domain: 'Provision of Supports',
    displayName: 'Participant money/property policy',
    description: 'A documented policy must govern how participant money and property are managed, including safeguards against misuse.',
    officialRef: 'Practice Standards, Verification Module, Outcome 2.4',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Documented policy for management of participant money and property exists and is current',
    evidenceRequired: 'Financial management procedure for participant funds',
    remediation: 'Create a participant money and property management policy covering handling procedures, segregation of funds, and oversight controls.',
  },
  {
    code: 'SEC-001',
    domain: 'Data Security',
    displayName: 'Australian data residency for all participant records',
    description: 'All participant personal information must be stored on servers located within Australia unless explicit informed consent is given for offshore storage.',
    officialRef: 'Privacy Act 1988, APP 8',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'All systems storing participant data are confirmed to use Australian-based data centres',
    evidenceRequired: 'Documentation confirming Australian storage location',
    remediation: 'Confirm data residency with all vendors. Migrate any offshore data to Australian data centres. Obtain vendor attestation letters.',
  },
  {
    code: 'SEC-011',
    domain: 'Data Security',
    displayName: '7-year retention lock on records',
    description: 'All participant records must be retained for a minimum of 7 years from the date the service was last provided, with deletion prevention controls.',
    officialRef: 'NDIS (Provider Registration) Rules 2018, Rule 15(2)',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Records retention policy specifies 7-year minimum and system prevents early deletion',
    evidenceRequired: 'Records retention policy + system configuration evidence',
    remediation: 'Implement 7-year retention policy. Configure system-level deletion locks. Document policy and provide system configuration evidence.',
  },
  {
    code: 'ONB-P-001',
    domain: 'Participant Onboarding',
    displayName: 'Participant cannot be active until intake complete',
    description: 'No services may be delivered to a participant until the full intake and onboarding process is completed, including agreement, consent, and plan verification.',
    officialRef: 'Practice Standards, Verification Module, Outcome 2.1',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'All active participants have a completed onboarding checklist dated before their first service record',
    evidenceRequired: 'Onboarding checklist showing completion before service start',
    remediation: 'Implement onboarding checklist as prerequisite for service commencement. Review any participants who received services before completing onboarding.',
  },
  {
    code: 'ONB-P-002',
    domain: 'Participant Onboarding',
    displayName: 'Agreement signed before first service date',
    description: 'The service agreement must be signed by the participant (or their nominee) before the first service is delivered.',
    officialRef: 'Practice Standards, Verification Module, Outcome 2.3',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Service agreement signature date is on or before the first service delivery date for every participant',
    evidenceRequired: 'Agreement date ≤ first service date per participant',
    remediation: 'Ensure agreement signing is a prerequisite workflow step. Audit existing participants for agreement date vs first service date compliance.',
  },
  {
    code: 'ONB-S-001',
    domain: 'Staff Onboarding',
    displayName: 'Worker cannot be assigned until onboarding complete',
    description: 'Workers must complete all onboarding requirements (screening, orientation, Code of Conduct) before being assigned to work with participants.',
    officialRef: 'Practice Standards (Worker Screening) Rules 2018',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'All active workers have a completed onboarding record dated before their first participant assignment',
    evidenceRequired: 'Onboarding record completed before first assignment',
    remediation: 'Implement worker onboarding checklist as prerequisite for assignment. Stand down any workers assigned before completing onboarding.',
  },
  {
    code: 'ONB-S-002',
    domain: 'Staff Onboarding',
    displayName: 'Screening clearance before first shift',
    description: 'Workers must have their NDIS Worker Screening Check clearance confirmed before working their first shift.',
    officialRef: 'Practice Standards (Worker Screening) Rules 2018',
    qualityIndicatorRef: null,
    severity: 'CRITICAL',
    weight: -25,
    condition: 'Screening clearance date is on or before first shift date for every worker',
    evidenceRequired: 'Screening clearance date ≤ first shift date',
    remediation: 'Confirm screening clearance before rostering workers. Do not allow shift commencement without verified clearance.',
  },

  // ─── MAJOR (weight: -10) ──────────────────────────────────────────────
  {
    code: 'REG-003',
    domain: 'Registration',
    displayName: 'Renewal application lodged 6+ months before expiry',
    description: 'Registration renewal must be lodged at least 6 months before expiry to ensure continuity of registration.',
    officialRef: 'Provider Registration Rules 2018, Rule 12',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Renewal application lodgement date is at least 6 months before registration expiry date',
    evidenceRequired: 'Evidence of renewal lodgement with date',
    remediation: 'Set calendar reminder for 8 months before expiry. Lodge renewal application immediately if within 6-month window.',
  },
  {
    code: 'REG-008',
    domain: 'Registration',
    displayName: 'Key personnel suitability declarations within 12 months',
    description: 'All key personnel must have submitted suitability declarations within the last 12 months.',
    officialRef: 'Provider Registration Rules 2018, Rule 10',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'All key personnel have a suitability declaration dated within the last 12 months',
    evidenceRequired: 'Dated declarations from key personnel',
    remediation: 'Collect fresh suitability declarations from all key personnel. Schedule annual renewal reminders.',
  },
  {
    code: 'REG-010',
    domain: 'Registration',
    displayName: 'ABN active and matches registration record',
    description: 'The provider\'s ABN must be active on the Australian Business Register and match the ABN on their NDIS registration.',
    officialRef: 'NDIS Act 2013, Section 73E',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'ABN is active on ABR and matches the registration certificate',
    evidenceRequired: 'ABN lookup confirmation',
    remediation: 'Verify ABN status on abr.business.gov.au. If mismatched, notify NDIS Commission of change of details.',
  },
  {
    code: 'GOV-004',
    domain: 'Governance',
    displayName: 'Corrective actions have owner + due date, none overdue >30 days',
    description: 'All corrective actions in the improvement register must have an assigned owner and due date, with no actions overdue by more than 30 days.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 73',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 73',
    severity: 'MAJOR',
    weight: -10,
    condition: 'All open corrective actions have an owner and due date, and none are overdue by more than 30 days',
    evidenceRequired: 'Improvement register with assigned owners and dates',
    remediation: 'Assign owners and due dates to all open actions. Escalate and close or re-date any actions overdue >30 days.',
  },
  {
    code: 'GOV-009',
    domain: 'Governance',
    displayName: 'Incident records retained 7 years',
    description: 'All incident records must be retained for a minimum of 7 years from the date of the incident.',
    officialRef: 'NDIS (Incident Management) Rules 2018, Rule 16',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Retention policy specifies 7-year minimum for incident records and system enforces it',
    evidenceRequired: 'Retention policy + system evidence',
    remediation: 'Update retention policy to specify 7-year minimum for incidents. Configure system to prevent deletion within retention period.',
  },
  {
    code: 'GOV-011',
    domain: 'Governance',
    displayName: 'Complaints policy references NDIS Commission contact',
    description: 'The complaints policy must include NDIS Commission contact details (1800 035 544 or ndiscommission.gov.au) for escalation.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 75',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 75',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Complaints policy document contains NDIS Commission contact number (1800 035 544) or website (ndiscommission.gov.au)',
    evidenceRequired: 'Policy text mentioning 1800 035 544 or ndiscommission.gov.au',
    remediation: 'Update complaints policy to include: "If you are not satisfied with our response, you can contact the NDIS Quality and Safeguards Commission on 1800 035 544 or ndiscommission.gov.au"',
  },
  {
    code: 'GOV-012',
    domain: 'Governance',
    displayName: 'Complaint records retained 7 years',
    description: 'All complaint records must be retained for a minimum of 7 years from resolution.',
    officialRef: 'NDIS (Complaints) Rules 2018, Rule 10',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Retention policy specifies 7-year minimum for complaint records and system enforces it',
    evidenceRequired: 'Retention policy + system evidence',
    remediation: 'Update retention policy to include 7-year minimum for complaints. Ensure system prevents premature deletion.',
  },
  {
    code: 'GOV-013',
    domain: 'Governance',
    displayName: 'Risk register reviewed within 12 months',
    description: 'The organisational risk register must be reviewed at least annually, with documented review date and outcomes.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 73',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 73',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Risk register has a documented review date within the last 12 months',
    evidenceRequired: 'Risk register with review date within last 12 months',
    remediation: 'Conduct risk register review immediately. Document review date, attendees, and any changes made.',
  },
  {
    code: 'WF-002',
    domain: 'Workforce',
    displayName: 'Screening records retained 7 years',
    description: 'Worker screening records must be retained for 7 years after the worker ceases engagement.',
    officialRef: 'Practice Standards (Worker Screening) Rules 2018',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Retention policy specifies 7-year minimum for screening records post-engagement',
    evidenceRequired: 'Retention policy confirmation',
    remediation: 'Update retention policy to cover worker screening records for 7 years post-engagement. Verify no records have been prematurely destroyed.',
  },
  {
    code: 'WF-004',
    domain: 'Workforce',
    displayName: 'NDIS Worker Orientation Module completed',
    description: 'All workers must complete the NDIS Worker Orientation Module ("Quality, Safety and You") and have a certificate on file.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 77',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 77',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Orientation Module certificate on file for every active worker',
    evidenceRequired: 'Orientation certificates on file per worker',
    remediation: 'Direct all workers without certificates to complete the free module at ndiscommission.gov.au. Collect and file certificates.',
  },
  {
    code: 'WF-006',
    domain: 'Workforce',
    displayName: 'Role-mapped qualifications and mandatory training current',
    description: 'Workers must hold qualifications and training appropriate to their role, with records of completion and currency.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 77',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 77',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Training register shows all required training current for each worker based on their role requirements',
    evidenceRequired: 'Training register with completion dates',
    remediation: 'Map mandatory training to roles. Identify gaps and schedule training. Update training register with completion evidence.',
  },
  {
    code: 'WF-010',
    domain: 'Workforce',
    displayName: 'Volunteers/contractors held to same screening rules',
    description: 'Volunteers and contractors providing supports must meet the same screening requirements as employed workers.',
    officialRef: 'Practice Standards (Worker Screening) Rules 2018',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'All active volunteers and contractors have valid screening clearances or documented exemptions',
    evidenceRequired: 'Contractor screening evidence or exemption documentation',
    remediation: 'Require screening clearances from all contractors/volunteers before engagement. Document any exemptions with rationale.',
  },
  {
    code: 'POS-008',
    domain: 'Provision of Supports',
    displayName: 'Agreement prices consistent with current Pricing Arrangements',
    description: 'Service agreement pricing must not exceed the NDIS Pricing Arrangements and Price Limits for the current period.',
    officialRef: 'NDIS Pricing Arrangements 2025-26',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'All service agreement prices are at or below current NDIS price limits for their support category',
    evidenceRequired: 'Service agreement fees matching current price limits',
    remediation: 'Review all agreement pricing against current Pricing Arrangements. Amend any agreements exceeding price limits.',
  },
  {
    code: 'POS-010',
    domain: 'Provision of Supports',
    displayName: 'PM invoices within SLA, monthly statements, payments reconciled',
    description: 'Plan management operations must process invoices within SLA, send monthly statements, and reconcile all payments.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 74',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 74',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Invoice processing meets SLA, monthly statements sent, and payment reconciliation is current',
    evidenceRequired: 'Payment processing records, statement delivery timestamps',
    remediation: 'Review invoice processing times. Send outstanding statements. Reconcile payment records and resolve discrepancies.',
  },
  {
    code: 'SLA-002',
    domain: 'Service Levels',
    displayName: 'Complaint acknowledged within 2 business days',
    description: 'All complaints must be acknowledged to the complainant within 2 business days of receipt.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 75',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 75',
    severity: 'MAJOR',
    weight: -10,
    condition: 'All complaints have an acknowledgement record within 2 business days of lodgement',
    evidenceRequired: 'Complaints register showing acknowledgement timestamps',
    remediation: 'Implement 2-business-day acknowledgement SLA in complaints process. Set up automated acknowledgement or daily review of new complaints.',
  },
  {
    code: 'SLA-005',
    domain: 'Service Levels',
    displayName: 'PM invoices paid/queried within 5 business days',
    description: 'Plan management must process (pay or query) provider invoices within 5 business days of receipt.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 74',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 74',
    severity: 'MAJOR',
    weight: -10,
    condition: 'All invoices are paid or queried within 5 business days of receipt',
    evidenceRequired: 'Invoice processing time reports',
    remediation: 'Review invoice processing workflows. Allocate resources to clear backlog. Implement 5-day processing SLA monitoring.',
  },
  {
    code: 'SLA-006',
    domain: 'Service Levels',
    displayName: 'Monthly statements sent by the 10th',
    description: 'Participant monthly statements must be distributed by the 10th of the following month.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 74',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 74',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Monthly statements delivered to all participants by the 10th of each month',
    evidenceRequired: 'Statement delivery timestamps from CareSquare',
    remediation: 'Configure automated statement generation by 8th of month. Monitor delivery and follow up on failures.',
  },
  {
    code: 'SLA-007',
    domain: 'Service Levels',
    displayName: 'Services claimed within 90-day window',
    description: 'All claims must be submitted to the NDIA within 90 days of the service delivery date.',
    officialRef: 'NDIS Pricing Arrangements 2025-26, Section 3.2',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'All claims are submitted within 90 days of the service date',
    evidenceRequired: 'Claims submission date vs service date evidence',
    remediation: 'Implement 60-day warning alerts for unclaimed services. Process outstanding claims immediately. Review workflow for claim submission delays.',
  },
  {
    code: 'SEC-003',
    domain: 'Data Security',
    displayName: 'MFA enforced for all accounts with participant data access',
    description: 'Multi-factor authentication must be enforced for all user accounts that can access participant personal information.',
    officialRef: 'Privacy Act 1988, APP 11',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'MFA is enabled and enforced for all accounts with access to participant data',
    evidenceRequired: 'MFA configuration evidence',
    remediation: 'Enable MFA on all systems storing participant data. Enforce MFA policy — disable accounts that do not comply within 7 days.',
  },
  {
    code: 'SEC-006',
    domain: 'Data Security',
    displayName: 'Backups verified and restore tested within 12 months',
    description: 'Data backups must be verified regularly and a restore test performed at least annually.',
    officialRef: 'Privacy Act 1988, APP 11',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Backup verification logs exist and a successful restore test was performed within the last 12 months',
    evidenceRequired: 'Backup verification logs + restore test record',
    remediation: 'Schedule and perform a backup restore test. Document results including data integrity verification. Set annual calendar reminder.',
  },
  {
    code: 'SEC-008',
    domain: 'Data Security',
    displayName: 'Data breach response plan referencing OAIC',
    description: 'A data breach response plan must be documented, including OAIC notification requirements under the Notifiable Data Breaches scheme.',
    officialRef: 'Privacy Act 1988, Part IIIC',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Data breach response plan exists and references OAIC notification requirements',
    evidenceRequired: 'Data breach response plan document',
    remediation: 'Create data breach response plan covering identification, containment, assessment, notification (OAIC within 30 days if eligible), and review.',
  },
  {
    code: 'ONB-P-010',
    domain: 'Participant Onboarding',
    displayName: 'PM onboarding includes written advice on invoices, statements, queries',
    description: 'Plan management participant onboarding must include written information about how invoices are processed, when statements are sent, and how to raise queries.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 74',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 74',
    severity: 'MAJOR',
    weight: -10,
    condition: 'Onboarding documentation includes written advice on invoice processing, statements, and query procedures',
    evidenceRequired: 'Welcome email or onboarding documentation',
    remediation: 'Update onboarding pack/welcome email to include clear information about invoice processing times, statement schedule, and how to raise queries.',
  },
  {
    code: 'ONB-P-011',
    domain: 'Participant Onboarding',
    displayName: 'Exit checklist — final statement, handover, records transfer',
    description: 'When a participant exits, a checklist must be completed covering final statement, handover to new provider, and records transfer.',
    officialRef: 'Practice Standards, Verification Module, Outcome 2.1',
    qualityIndicatorRef: null,
    severity: 'MAJOR',
    weight: -10,
    condition: 'Exit checklist completed for all exited participants covering final statement, handover, and records transfer',
    evidenceRequired: 'Exit procedure documentation',
    remediation: 'Create exit checklist template. Apply to all future exits. Backfill documentation for recent exits where possible.',
  },

  // ─── MINOR (weight: -3) ───────────────────────────────────────────────
  {
    code: 'RR-007',
    domain: 'Rights & Responsibilities',
    displayName: 'Consent re-confirmed within 24 months or on change',
    description: 'Participant consent must be re-confirmed at least every 24 months or when there is a material change to services or information handling.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 73',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 73',
    severity: 'MINOR',
    weight: -3,
    condition: 'All active participants have consent confirmation dated within the last 24 months',
    evidenceRequired: 'Re-confirmation records with dates',
    remediation: 'Schedule consent re-confirmation at plan review or 24-month anniversary. Contact participants due for renewal.',
  },
  {
    code: 'SEC-009',
    domain: 'Data Security',
    displayName: 'Password/secret policy documented',
    description: 'A documented password and secrets management policy must be in place covering complexity, rotation, and storage requirements.',
    officialRef: 'Privacy Act 1988, APP 11',
    qualityIndicatorRef: null,
    severity: 'MINOR',
    weight: -3,
    condition: 'Password/secrets management policy document exists and is current',
    evidenceRequired: 'Password policy document',
    remediation: 'Create password policy covering minimum length, complexity, rotation frequency, and prohibition of shared credentials.',
  },
  {
    code: 'SEC-010',
    domain: 'Data Security',
    displayName: 'Vendor/third-party data handling assessed annually',
    description: 'All third-party vendors handling participant data must be assessed annually for data handling practices and compliance.',
    officialRef: 'Privacy Act 1988, APP 8',
    qualityIndicatorRef: null,
    severity: 'MINOR',
    weight: -3,
    condition: 'Annual vendor assessment records exist for all vendors with access to participant data',
    evidenceRequired: 'Vendor assessment records dated within 12 months',
    remediation: 'Create vendor register. Conduct annual assessments of data handling practices. Document findings and any required actions.',
  },
  {
    code: 'SLA-009',
    domain: 'Service Levels',
    displayName: 'Corrective action SLA: CRITICAL ≤7d, MAJOR ≤30d, MINOR ≤90d',
    description: 'Corrective actions must be resolved within severity-based timeframes: critical within 7 days, major within 30 days, minor within 90 days.',
    officialRef: 'Quality Indicators 2018, Part 9, Section 73',
    qualityIndicatorRef: 'Quality Indicators 2018, Part 9, Section 73',
    severity: 'MINOR',
    weight: -3,
    condition: 'All corrective actions are resolved within their severity-based SLA timeframe',
    evidenceRequired: 'Corrective action register with resolution dates within SLA',
    remediation: 'Review overdue corrective actions. Escalate critical items. Assign resources to clear backlog within SLA timeframes.',
  },

  // ─── ADVISORY (weight: -1) ────────────────────────────────────────────
  {
    code: 'FUT-001',
    domain: 'Future Readiness',
    displayName: 'Reform watchlist — Commission changes acknowledged within 14 days',
    description: 'The organisation monitors NDIS Commission announcements and acknowledges/assesses new requirements within 14 days of publication.',
    officialRef: 'N/A — best practice',
    qualityIndicatorRef: null,
    severity: 'ADVISORY',
    weight: -1,
    condition: 'Reform watchlist shows all Commission announcements acknowledged within 14 days',
    evidenceRequired: 'Watchlist register with acknowledgement dates',
    remediation: 'Subscribe to NDIS Commission updates. Assign responsibility for monitoring and documenting acknowledgement of changes.',
  },
  {
    code: 'FUT-004',
    domain: 'Future Readiness',
    displayName: 'PM panel readiness ahead of ~Oct 2027',
    description: 'The organisation is preparing for the announced plan management panel arrangement expected around October 2027, including capability self-assessment.',
    officialRef: 'N/A — announced reform',
    qualityIndicatorRef: null,
    severity: 'ADVISORY',
    weight: -1,
    condition: 'Documentation of panel readiness preparation activities exists',
    evidenceRequired: 'Panel readiness self-assessment or preparation plan',
    remediation: 'Begin panel readiness self-assessment. Document current capabilities against expected panel criteria. Create improvement plan for gaps.',
  },
  {
    code: 'POS-007',
    domain: 'Provision of Supports',
    displayName: 'Plan utilisation projection — flags >20% burn-rate variance',
    description: 'Proactive monitoring of plan utilisation with alerts when spend rate varies more than 20% from expected trajectory.',
    officialRef: 'N/A — best practice',
    qualityIndicatorRef: null,
    severity: 'ADVISORY',
    weight: -1,
    condition: 'Plan utilisation monitoring is active and flags variance >20% from expected burn rate',
    evidenceRequired: 'Utilisation report or dashboard showing variance monitoring',
    remediation: 'Implement plan utilisation tracking. Configure alerts for >20% variance. Review flagged plans with participants.',
  },
  {
    code: 'SLA-011',
    domain: 'Service Levels',
    displayName: 'Rolling 90-day SLA breach-rate dashboard',
    description: 'A dashboard or report showing rolling 90-day SLA breach rates across all service level commitments.',
    officialRef: 'N/A — best practice',
    qualityIndicatorRef: null,
    severity: 'ADVISORY',
    weight: -1,
    condition: 'SLA breach-rate dashboard or report exists and is current (within last 7 days)',
    evidenceRequired: 'Dashboard screenshot or report showing 90-day SLA performance',
    remediation: 'Build SLA performance dashboard showing breach rates over rolling 90-day window. Review weekly in team meeting.',
  },
  {
    code: 'SLA-012',
    domain: 'Service Levels',
    displayName: 'Agreement promise parser — AI extracts committed timeframes',
    description: 'Automated extraction of committed timeframes from service agreements to populate SLA monitoring.',
    officialRef: 'N/A — best practice',
    qualityIndicatorRef: null,
    severity: 'ADVISORY',
    weight: -1,
    condition: 'Automated or semi-automated process extracts SLA commitments from service agreements',
    evidenceRequired: 'Extracted SLA commitments mapped to monitoring system',
    remediation: 'Implement agreement parsing (manual or AI-assisted) to extract timeframe commitments. Map to SLA monitoring dashboard.',
  },
]

async function main() {
  let count = 0
  for (const rule of rules) {
    await prisma.rule.upsert({
      where: { code: rule.code },
      update: { ...rule },
      create: { ...rule },
    })
    count++
  }
  console.log(`Seeded ${count} rules`)
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e)
    prisma.$disconnect()
    process.exit(1)
  })
