import { NextRequest, NextResponse } from 'next/server'
import { generateText } from '@/lib/ai'
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx'

export async function POST(request: NextRequest) {
  try {
    const { checklistId, itemName, context, ruleCode, issue } = await request.json()

    const docName = itemName || ruleCode || 'Compliance Document'

    const prompt = `Generate a complete "${docName}" document for an NDIS Plan Management provider.

Provider: 24 Seven Plan Management
Participants: 1100+
Staff: 3 (Plan Manager, Assistant Plan Manager, Community Relations Manager)
Registration group: 0127 (Plan Management)
Audit pathway: Verification

${context ? `Additional context: ${context}` : ''}
${issue ? `Issue to address: ${issue}` : ''}

Create a professional, audit-ready document. Return as JSON:
{
  "title": "Document Title",
  "subtitle": "24 Seven Plan Management",
  "version": "1.0",
  "date": "${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}",
  "sections": [
    {
      "heading": "Section Title",
      "paragraphs": ["Paragraph 1 text...", "Paragraph 2 text..."]
    }
  ]
}

Requirements:
- Professional language suitable for an NDIS auditor
- Reference relevant legislation (NDIS Act 2013, Privacy Act 1988, etc.)
- Include specific details for Plan Management (financial administration, invoice processing, monthly statements)
- Minimum 4-5 sections with substantive content
- Each section should have 2-4 paragraphs
- Be specific, not generic — reference the actual services (budget management, claims processing, provider payments)`

    const result = await generateText(prompt, undefined, { temperature: 0.3, maxOutputTokens: 4096 })

    if (result.isMock) {
      return NextResponse.json({ error: 'AI unavailable' }, { status: 503 })
    }

    let docContent: { title: string; subtitle?: string; version?: string; date?: string; sections: Array<{ heading: string; paragraphs: string[] }> }
    try {
      let cleaned = result.text.trim()
      if (cleaned.startsWith('```')) cleaned = cleaned.substring(cleaned.indexOf('\n') + 1)
      if (cleaned.endsWith('```')) cleaned = cleaned.substring(0, cleaned.lastIndexOf('```'))
      docContent = JSON.parse(cleaned.trim())
    } catch {
      return NextResponse.json({ error: 'Failed to generate document content' }, { status: 500 })
    }

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            children: [new TextRun({ text: docContent.title, bold: true, size: 48, font: 'Calibri' })],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: docContent.subtitle || '24 Seven Plan Management', italics: true, size: 24, color: '666666' }),
            ],
            spacing: { after: 50 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Version ${docContent.version || '1.0'} | ${docContent.date || new Date().toLocaleDateString('en-AU')}`, size: 20, color: '999999' }),
            ],
            spacing: { after: 400 },
          }),
          ...docContent.sections.flatMap(section => [
            new Paragraph({
              children: [new TextRun({ text: section.heading, bold: true, size: 28, font: 'Calibri' })],
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 300, after: 120 },
            }),
            ...section.paragraphs.map(para =>
              new Paragraph({
                children: [new TextRun({ text: para, size: 22, font: 'Calibri' })],
                spacing: { after: 120 },
              })
            ),
          ]),
          new Paragraph({ spacing: { before: 600 } }),
          new Paragraph({
            children: [new TextRun({ text: '— End of Document —', italics: true, size: 18, color: '999999' })],
          }),
          new Paragraph({
            children: [new TextRun({ text: `Generated by AuditReady | ${new Date().toLocaleDateString('en-AU')}`, size: 16, color: 'BBBBBB' })],
          }),
        ],
      }],
    })

    const buffer = await Packer.toBuffer(doc)
    const filename = `${docContent.title.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '_')}.docx`

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    console.error('[documents/generate]', error)
    return NextResponse.json({ error: 'Document generation failed' }, { status: 500 })
  }
}
